### ISSUE TITLE
Error 500 - nova-api/scripts/rut-fiel 

### ISSUE THREAD

**Issue by miharbi** [freshworkstudio/nova-rut-field#1]
Hi firts at all good, work with this repo and with ChileanBundle.

Im getting an error, are there more steps for the instalation? 
"GET http://nova.local/nova-api/styles/rut-field net::ERR_ABORTED 500 (Internal Server Error)"

Here my code
``` 
use Freshwork\ChileanBundle\Rut;
use Freshwork\RutField\RutField;

public function fields(Request $request)
    {
        return [
            RutField::make('Rut', 'rut')
                ->rules('required', 'cl_rut')
                ->displayUsing(function ($rut) {
                    return Rut::parse($rut)->format();
                })
                ->sortable(),
        ];
    }

**Comment by rodrigore** [comment]
You need to generate de assets in order to generate the 'dist' folder.

You can run: npm run dev, npm run watch or npm run prod in the root of the package folder.

For example I installed this package and run all this command:

* git clone  https://github.com/freshworkstudio/nova-rut-field
* cd nova-rut-field
* npm install
* npm run dev

**Comment by gdespirito** [comment]
Sorry, you're right. I just updated the package to add more options and fixing the 500 problem. The README it is also updated :)

**Comment by gdespirito** [comment]
Be sure to use version 1.1.1 when doing `composer update`
